[platformio]
src_dir = .

[env:waveshare_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX@^1.1
    h2zero/NimBLE-Arduino
    lvgl/lvgl
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I.
board_build.arduino.flash_size = 8MB
board_build.arduino.psram = true
